### PR TITLE
added flask_script dependency

### PR DESCRIPTION
**Pull request by sairamch04**

### CODE REVIEW

**Comment by mayank-ism** [comment]
Why did you close this?

**Comment by sairamch04** [comment]
This file has all the required dependencies but It appears unnecessary dependencies are also  included.

**Comment by sairamch04** [comment]
The existing requirements file  does not have all the required dependencies. So re-opening this

**Comment by mayank-ism** [comment]
Can you sort out unnecessary dependencies? 

That would be great!

**Pull request closed without merging**
